"""Mejora a Carreras

Revision ID: 171999bd608f
Revises: 3267f7fcd022
Create Date: 2026-05-23 17:00:37.335591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '171999bd608f'
down_revision: Union[str, Sequence[str], None] = '3267f7fcd022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carreras', sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('Carreras', 'nombre_carrera')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carreras', sa.Column('nombre_carrera', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Carreras', 'nombre')
    # ### end Alembic commands ###
