"""tablas iniciales

Revision ID: f17f9b8bf717
Revises:
Create Date: 2026-05-22 20:34:36.430049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "f17f9b8bf717"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Carreras",
        sa.Column("nombre_carrera", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Categorias",
        sa.Column("tipo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Equipos",
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Torneos",
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Jugadores",
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("puntaje", sa.Integer(), nullable=True),
        sa.Column("generacion", sa.Date(), nullable=True),
        sa.Column("carrera_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carrera_id"],
            ["Carreras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Torneos_Categorias",
        sa.Column("torneo_id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["Categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["torneo_id"],
            ["Torneos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Fases",
        sa.Column("torneo_categoria_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["torneo_categoria_id"],
            ["Torneos_Categorias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Inscripciones",
        sa.Column("fecha", sa.Date(), nullable=True),
        sa.Column("equipo_id", sa.Integer(), nullable=False),
        sa.Column("torneo_categoria_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipo_id"],
            ["Equipos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["torneo_categoria_id"],
            ["Torneos_Categorias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Jugador_Equipo",
        sa.Column("puntaje", sa.Integer(), nullable=True),
        sa.Column("jugador_id", sa.Integer(), nullable=False),
        sa.Column("equipo_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipo_id"],
            ["Equipos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["jugador_id"],
            ["Jugadores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Partidos",
        sa.Column("fase_id", sa.Integer(), nullable=False),
        sa.Column("partido_siguiente_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fase_id"],
            ["Fases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partido_siguiente_id"],
            ["Partidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Partidos_Equipos",
        sa.Column("ganador", sa.Boolean(), nullable=True),
        sa.Column("equipo_id", sa.Integer(), nullable=False),
        sa.Column("partido_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipo_id"],
            ["Equipos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partido_id"],
            ["Partidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Secciones",
        sa.Column("partido_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["partido_id"],
            ["Partidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Puntajes_De_Equipos",
        sa.Column("partido_equipo_id", sa.Integer(), nullable=False),
        sa.Column("seccion_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("puntaje", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["partido_equipo_id"],
            ["Partidos_Equipos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seccion_id"],
            ["Secciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Puntajes_De_Equipos")
    op.drop_table("Secciones")
    op.drop_table("Partidos_Equipos")
    op.drop_table("Partidos")
    op.drop_table("Jugador_Equipo")
    op.drop_table("Inscripciones")
    op.drop_table("Fases")
    op.drop_table("Torneos_Categorias")
    op.drop_table("Jugadores")
    op.drop_table("Torneos")
    op.drop_table("Equipos")
    op.drop_table("Categorias")
    op.drop_table("Carreras")
    # ### end Alembic commands ###
